name: AdvancedReplay
version: ${project.version}
main: me.jumper251.replay.ReplaySystem
author: Jumper251
depend: [ProtocolLib, VagtSystem, PlexCore]
commands:
  replay:
    description: Main Replay command
    aliases: [rp]
  vagtreplay:
    aliases: vr